[toolchain]


[features]
resolution = true
seeds=true
skip-lint = false

[programs.localnet]
smart_contract_counter = "9AMX3iy96Pu2Y7wuHg6aF8dTQDBFvnZmnhpqTFg4DxmC"
[programs.devnet]
smart_contract_counter="9AMX3iy96Pu2Y7wuHg6aF8dTQDBFvnZmnhpqTFg4DxmC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
